apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-quadra
  labels:
    app: quadra1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quadra1
  template:
    metadata:
      labels:
        app: quadra1
    spec:
      containers:
      - name: my-jekyll
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data-volume
        ports:
        - containerPort: 80
      volumes:
      - name: data-volume
        hostPath:
      # directory location on host
          path: /home/anju/data/QuadraLogics.github.io/_site
      # this field is optional
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: quadra-service
spec:
  type: NodePort
  selector:
    app: quadra1
  ports:
  - port: 80

                           
